'use strict';

let cities = ['Belém - BEL',
  'Rio de Janeiro - Galeão - GIG',
  'Aalborg - AAL',
  'Aberdeen - ABZ',
  'Aeroporto de Zurique - ZHR',
  'Água Boa - QAA',
  'Alesund - AES',
  'Almeirim - QAB',
  'Altamira - ATM',
  'Amsterdam - Schiphol - AMS',
  'Aracaju - AJU',
  'Araçatuba - ARU',
  'Araguaína - AUX',
  'Arapongas - APX',
  'Assunção - ASU',
  'Atlanta - ATL',
  'Austin - US - AUS',
  'Bagé - BGX',
  'Bahía Blanca - BHI',
  'Barbados - BGI',
  'Barcelona - El Prat - BCN ',
  'Barcelos - BAZ',
  'Bariloche - BRC',
  'Barreiras - BRA',
  'Barretos - BAT',
  'Belém - BEL',
  'Belo Horizonte - Confins - CNF',
  'Belo Horizonte - Pampulha - PLU',
  'Belo Horizonte - Todos os Aeroportos - BHZ',
  'Bergen - Flesland - BGO',
  'Berlin - Tegel Airport - TXL',
  'Bilbao - BIO ',
  'Billund - BLL',
  'Birmingham - BHX',
  'Boa Vista - BVB',
  'Bolonha - BLQ',
  'Bordeaux Airport - BOD',
  'Boston - BOS',
  'Brasília - BSB',
  'Bremen Airport - BRE',
  'Brest - BES',
  'Breves - BVS',
  'Bristol - BRS',
  'Buenos Aires - Ezeiza - EZE',
  'Buenos Aires - Todos os Aeroportos - BUE',
  'Buenos Aires - Aeroparque - AEP',
  'Cabo Frio - CFB',
  'Caldas Novas - CLV',
  'Calgary - YYC',
  'Campina Grande - CPV',
  'Campinas - Viracopos - VCP',
  'Campo Grande - CGR',
  'Campo Mourão - CBW',
  'Cancun International Airport - CUN',
  'Carajás - CKS',
  'Carauari - CAF',
  'Cardiff - CWL',
  'Cascavel - CAC',
  'Catamarca - CTC',
  'Caxias do Sul - CXJ',
  'Chapecó - XAP',
  'Charlotte - CLT',
  'Chicago - ORD',
  'Cianorte - QCN',
  'Cidade do México - MEX',
  'Cidade do Panamá - PTY',
  'Cincinnati - CVG',
  'Clermont - Ferrand - CFE',
  'Comodoro Rivadavia - CRD',
  'Copenhagen - Kastrup - CPH',
  'Córdoba - COR',
  'Cornélio Procópio - CKO',
  'Corrientes - CNQ',
  'Cruzeiro do Sul - CZS',
  'Cuiabá - CGB',
  'Curitiba - CWB',
  'Dallas - Fort Worth - DFW',
  'Denver - DEN',
  'Detroit - Todos os Aeroportos - DTT',
  'Detroit - DTW',
  'Dourados - DOU',
  'Dublin - DUB',
  'Duesseldorf International - DUS',
  'Durham - MME',
  'Edinburgh - EDI',
  'El Calafate - FTE',
  'Esquel - EQS',
  'Estocolmo - Arlanda - ARN',
  'EuroAirport Basel - Mulhouse - Freiburg - BSL',
  'Fernando de Noronha - FEN',
  'Filadelfia - PHL',
  'Florença - FLR',
  'Florianópolis - FLN',
  'Formosa - FMA',
  'Fortaleza - FOR',
  'Foz do Iguaçu - IGU',
  'Franca - FRC',
  'Francisco Beltrão - FBE',
  'Frankfurt International Airport - FRA',
  'Genebra - GVA',
  'Gênova - GOA',
  'Glasgow - GLA',
  'Goiânia - GYN',
  'Gotemburgo - Landvetter - GOT',
  'Governador Valadares - GVR',
  'Guadalajara - GDL',
  'Guaira - QGA',
  'Guayaquil - Jose Joaquin de Olmedo - GYE',
  'Hamburg Airport - HAM',
  'Hannover Airport - HAJ',
  'Honolulu, US - - HNL',
  'Houma - Terrebonne Airport - HUM',
  'Houston - Todos os Aeroportos - HOU',
  'Houston - IAH',
  'Humberside - HUY',
  'Ilha Galápagos - Baltra - GPS',
  'Ilhéus - IOS',
  'Indianapolis - IND',
  'Ipatinga - IPN',
  'Istambul - IST',
  'Itaituba - ITB',
  'Jericoacoara - JJD',
  'João Pessoa - JPA',
  'Joinville - JOI',
  'Juazeiro do Norte - JDO',
  'Juína - JIA',
  'Juiz de Fora – Zona da Mata - IZA',
  'Jujuy - JUJ',
  'Kristiansand - KRS',
  'La Rioja - IRJ',
  'Lábrea - LBR',
  'Las Vegas - US - LAS',
  'Leeds / Bradford - LBA',
  'León - BJX',
  'Lima - LIM',
  'Linkoping - LPI',
  'Lisboa - LIS',
  'London - LHR',
  'Londrina - LDB',
  'Los Angeles - LAX',
  'Lyon Satolas Airport - LYS',
  'Macapá - MCP',
  'Maceió - MCZ',
  'Madrid - Barajas - MAD ',
  'Manaus - MAO',
  'Manchester - MAN',
  'Mar del Plata - MDQ',
  'Marabá - MAB',
  'Marília - MII',
  'Maringá - MGF',
  'Marseille - MRS',
  'Maués - MBZ',
  'Mendoza - MDZ',
  'Miami - MIA',
  'Minneapolis - MSP',
  'Monte Dourado - MEU',
  'Monterrey - MTY',
  'Montes Claros - MOC',
  'Montevidéu - MVD',
  'Montpellier - MPL',
  'Montreal - YUL',
  'Munich International - MUC',
  'Nantes - Atlantique Airport - NTE',
  'Nápoles - NAP',
  'Natal - NAT',
  'Navegantes - NVT',
  'Neuquén - NQN',
  'Newcastle - NCL',
  'Nice - NCE',
  'Norwich - NWI',
  'Nova Iorque - Todos os Aeroportos - NYC',
  'Nova Iorque - John F.Kennedy - JFK',
  'Nova Iorque - La Guardia - LGA',
  'Nova Iorque - Newark - EWR',
  'Nuremberg Airport - NUE',
  'Orlando - MCO',
  'Oslo - Gardermoen - OSL',
  'Oslo - Sandefjord - TRF',
  'Ottawa - YOW',
  'Palmas - PMW',
  'Paramaribo - PBM',
  'Paranaguá - PNG',
  'Paranavaí - PVI',
  'Parintins - PIN',
  'Paris - Charles De Gaulle - CDG',
  'Paris - Todos os Aeroportos - PAR',
  'Passo Fundo - - PFB',
  'Pau - PUF',
  'Petrolina - PNZ',
  'Phoenix - PHX',
  'Portland - PDX',
  'Porto Alegre - POA',
  'Porto de Moz - PTQ',
  'Porto Seguro - BPS',
  'Porto Velho - PVH',
  'Posadas - PSS',
  'Presidente Prudente - PPB',
  'Puerto Iguazú - IGR',
  'Punta Cana - PUJ',
  'Punta del Este - PDP',
  'Quito - UIO - Equador',
  'Raleigh / Durham - RDU',
  'Recife - REC',
  'Reina Beatrix Intl - AUA',
  'Rennes - RNS',
  'Resistencia - RES',
  'Ribeirão Preto - RAO',
  'Rio Branco - RBR',
  'Rio de Janeiro - Galeão - GIG',
  'Rio de Janeiro - Jacarepaguá - QJR',
  'Rio de Janeiro - Santos Dumont - SDU',
  'Rio de Janeiro - Todos os Aeroportos - RIO',
  'Rio Gallegos - RGL',
  'Rio Grande - RIG',
  'Rio Hondo - RHD',
  'Roma - Fiumicino - FCO',
  'Roma - Todos os Aeroportos - ROM',
  'Rondonópolis - ROO',
  'Rosario - ROS',
  'Saint Louis - STL',
  'Salt Lake City - SLC',
  'Salta - SLA',
  'Salvador - SSA',
  'San Diego - SAN',
  'San Francisco - SFO',
  'San José del Cabo - SJD',
  'San José, US - - SJC',
  'San Juan - UAQ',
  'San Luis - LUQ',
  'San Martin de los Andes - CPC',
  'San Rafael - AFA',
  'Santa Cruz de la Sierra - VVI',
  'Santa Fé - SNF',
  'Santa Rosa - SRA',
  'Santana do Livramento - RVY',
  'Santarém - STM',
  'Santiago - SCL',
  'Santiago del Estero - SDE',
  'São Borja - QOJ',
  'São Félix do Araguaia - SXO',
  'São Gabriel da Cachoeira - SJL',
  'São José do Rio Preto - SJP',
  'São Luis - SLZ',
  'São Paulo - Congonhas - CGH',
  'São Paulo - Guarulhos - GRU',
  'São Paulo - Todos os Aeroportos - SAO',
  'Seattle - SEA',
  'Simon Bolivar Intl - CCS',
  'Sinop - OPS',
  'Sorriso - SMT',
  'Stavanger - SVG',
  'Stuttgart - STR',
  'Tampa - TPA',
  'Tangará da Serra - TGQ',
  'Telêmaco Borba - TEK',
  'Teresina - THE',
  'Tijuana - TIJ',
  'Tobago - TAB',
  'Toronto - YYZ',
  'Toulouse - Blagnac Airport - TLS',
  'Trelew - REL',
  'Três Lagoas - TJL',
  'Trondheim - TRD',
  'Tucumán - TUC',
  'Turim - TRN',
  'Uberaba - UBA',
  'Uberlandia - UDI',
  'União da Vitória - QVB',
  'Ushuaia - USH',
  'Vail Eagle County - EGE',
  'Vancouver - YVR',
  'Veneza - VCE',
  'Verona - VRN',
  'Viedma - VDM',
  'Vitória - VIX',
  'Vitória da Conquista - VDC',
  'Washington - Dulles - IAD',
  'Washington - Ronald Reagan - DCA'];
console.log(cities);
